// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }

import React from "react";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { ThemeProvider } from "./context/DarkModeContext";
// import { DarkModeProvider } from "./context/DarkModeContext";

export const metadata = {
  title: "Resource Management System",
  description: "Generated by NOYT",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />
      </head>
      <body>
        <Toaster position="top-center" reverseOrder={false} />
        <ThemeProvider>{children}</ThemeProvider>
        {/* <DarkModeProvider>{children}</DarkModeProvider> */}
      </body>
    </html>
  );
}
